<?php

function cipher_menu(){
  $items['cipher'] = array(
    'title' => 'Cipher',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift Value',
    '#type' => 'textfield',
    '#description' => t('Enter shift value'),
  );
  $form['direction'] = array(
    '#title' => 'Direction',
    '#type' => 'textfield',
    '#description' => t('Enter Direction'),
  );
  $form['phrase'] = array(
    '#title' => 'Phrase',
    '#type' => 'textfield',
    '#description' => t('Enter phse to be encrypted'),
  );
  $form['submit'] = array(
  '#type' => 'submit',
  '#value' => 'Go',
  );
  return $form;
}

function cipher_form_submit($form, &$form_state){
  
}
